version: '3'
services: 


  web:
    image: nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./cache/:/cache/
    ports:
      - "5555:5555"
    depends_on:
      - py
    links:
      - py

  
  py:
    image: python
    ports:
      - "8085:8080"
    volumes:
      - ./app/:/app/
    working_dir: /app
    command: python app.py
    stdin_open: true
    tty: true


